### ISSUE TITLE
File name error

### ISSUE THREAD

**Issue by wonderfullyrich** [eribertomota/axel#44] opened 2017-01-28 00:24 UTC
Hi all,
I seem to be experiencing a file name parsing issue.  

I run
`axel -a -n 6 -v -s 204800 "https://something.url.com/d/p/longalphastring/Name%20of%20File.zip"`
and the file name the results in being downloaded is
"Name" rather than "Name of File.zip" which leads me to believe it's not parsing the spaces.

Other computers with axel (older OSX version and axel versions) run without this malformed name.  Also browsers (Safari, firefox, chrome, etc.) all seem to be able to handle the URL and generate the full file name.

Example:
```
axel -a -n 6 -v -s 204800 "https://something.url.com/d/p/longalphastring/Name%20of%20File.zip"
Initializing download: https://something.url.com/d/p/longalphastring/Name%20of%20File.zip
File size: 165596 bytes
Opening output file Name
Starting download

[  0%] [0                                 1                                 .2                                 3                                  4                                 5                                 ] [  76.2KB/s] [ 1h10]

```

Platform data:

macOS Sierra 10.12.2 (16C68)

```
axel: stable 2.12, HEAD
Light UNIX download accelerator
https://github.com/eribertomota/axel
/Users/rjeong/homebrew/Cellar/axel/2.12 (15 files, 133K) *
  Built from source on 2017-01-12 at 21:05:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/axel.rb
==> Dependencies
Build: autoconf ✔, automake ✔
Required: gettext ✔, openssl ✔
```

Thanks

**Comment by nemermollon** [comment] 2017-06-14 13:28
I think that i solved the problem

**Comment by nemermollon** [comment] 2017-06-14 13:38
See the pull request #53

**Comment by ismaell** [comment] 2017-07-16 05:57
Seems it's an OS-specific issue. More information is needed.

**Comment by ismaell** [comment] 2017-08-22 15:20
Doesn't seem so. I'm not sure if the bug was just fixed or the problem is with Mac OS X alone...

**Comment by ordex** [comment] 2017-08-22 15:21
mh, sorry, but I seriously think my comment was for another issue...not this one :( too many tabs open.

**Comment by ismaell** [comment] 2017-08-25 02:12
Can't reproduce it on Mac OS X 10.9. Closing.

**Closed by ismaell** 2017-08-25 02:12 UTC
Labels: bug, help wanted
