### ISSUE TITLE
cannot configure on CentOS6.9

### ISSUE THREAD

**Issue by HandsomeHans** [eribertomota/axel#55] opened 2017-06-23 01:27 UTC
I run ./autogen, I received:
"
configure.ac:46: warning: macro `AM_GNU_GETTEXT' not found in library
configure.ac:47: warning: macro `AM_GNU_GETTEXT_VERSION' not found in library
autoreconf: configure.ac: AM_GNU_GETTEXT_VERSION is used, but not AM_GNU_GETTEXT
Done. You can use the 'clean' option to vanish the source code.
Example of use: $ ./autogen.sh clean
Now run ./configure, make, and make install.
"

and then, when I run ./configure, an error occurred as below.
"
checking for library containing ERR_get_error... none required
./configure: line 4316: syntax error near unexpected token `external'
./configure: line 4316: `AM_GNU_GETTEXT(external)'
"

I can only install gettext-0.17 by yum, so I manually installed gettext-0.18 followed github, and also autoconf-2.69.
Anyone can help me? Thanks a lot!!!

**Comment by ismaell** [comment] 2017-07-01 11:17
Have you installed the `gettext-devel` package?

**Comment by HandsomeHans** [comment] 2017-07-03 05:57
@ismaell No! Maybe you are right! But I give it up, because I just cannot find a gettext-devel-0.18.2-el6 package for centos 6.9. Anyway, thank you very much!

**Comment by ismaell** [comment] 2017-07-16 06:29
OK. Closing. It's not a bug.

**Closed by ismaell** 2017-07-16 06:29 UTC
Labels: invalid
