### ISSUE TITLE
broken-point continuingly transferring

### ISSUE THREAD

**Issue by linglingtingfei** [eribertomota/axel#36] opened 2016-10-10 02:36 UTC
Does anyone know axel can achieve HTTP? Why do it restart to download files again other than continuing to transfer the last tasks when debugging?

**Comment by sdt** [comment] 2016-10-10 04:03
Sorry, could you be a little more specific please?

What are you trying to do? 
What are you expecting to happen? 
What is happening instead?

**Comment by linglingtingfei** [comment] 2016-10-10 07:37
Well, here's the thing: I'm downloading files using axel from website. Due to some error  occurred, the program was interrupted.
 After bug was fixed, the program restart to download again BUT the program didn't continue last task. This led to download duplicate files.
 In short, I want to axel can accomplish the same goal of the command “wget -c”.

**Comment by linglingtingfei** [comment] 2016-10-12 07:48
@sdt Could you answer my question? I'd appreciate that!

**Comment by sdt** [comment] 2016-10-12 21:17
My understanding is that axel *does* resume interrupted downloads. I'm not sure what's happened in your case sorry.

Can you provide a reproducible case where this doesn't happen?

**Comment by linglingtingfei** [comment] 2016-10-13 02:15
First, my code is `cat the-download-url.list | xargs -l1 axel -n 8 -a`; Then, I rerun the program, it outputted duplicated files like the below screenshot shown.
![image](https://cloud.githubusercontent.com/assets/20789616/19334259/48625e82-912d-11e6-9055-c43b384453c8.png)

**Comment by sdt** [comment] 2016-10-13 02:34
Ah, I see what's going on.

The downloads completed successfully, but then downloaded again when you asked to download them again.

The behaviour you're seeing is the intended behaviour, but I understand your use-case.

I've created a feature request for that in #37. 

I'll close this issue in preference to the new one. Let me know if you had something else in mind.

**Closed by sdt** 2016-10-13 02:34 UTC
